import type { ContentDocument } from './model'
import { availabilityDefaults } from './availability'
import { resourceFields } from './resources'

// Fixed page catalogue. Paths, images, forms and layouts are intentionally not editable.
// Defaults preserve the existing website until the first publication.
const pageDocuments: ContentDocument[] = [
  {
    id: "tci", label: "Taman Cibaduyut Indah", path: "/proyek/tci", category: "Komplek",
    fields: [
      {"key":"hero.title","label":"Judul halaman — Taman Cibaduyut Indah","group":"HERO","defaultValue":"Taman Cibaduyut Indah","kind":"text","maxLength":180},
      {"key":"hero.text","label":"Teks / label — Cibaduyut, Kota Bandung","group":"HERO","defaultValue":"Cibaduyut, Kota Bandung","kind":"text","maxLength":180},
      {"key":"hero.description","label":"Deskripsi — Pengembangan kawasan hunian terpadu yang meng…","group":"HERO","defaultValue":"Pengembangan kawasan hunian terpadu yang menggabungkan kenyamanan modern dengan lingkungan asri yang harmonis.","kind":"textarea","maxLength":3000},
      {"key":"section2.text","label":"Teks / label — TAMAN CIBADUYUT INDAH","group":"VISI KAWASAN","defaultValue":"TAMAN CIBADUYUT INDAH","kind":"text","maxLength":180},
      {"key":"section2.heading","label":"Judul bagian — Visi Kawasan Terintegrasi","group":"VISI KAWASAN","defaultValue":"Visi Kawasan Terintegrasi","kind":"text","maxLength":180},
      {"key":"section2.description","label":"Deskripsi — Kawasan Taman Cibaduyut Indah merupakan bagia…","group":"VISI KAWASAN","defaultValue":"Kawasan Taman Cibaduyut Indah merupakan bagian dari upaya Marga Tirta Kencana dalam menghadirkan hunian yang nyaman dan sesuai dengan kebutuhan keluarga modern. Berlokasi di kawasan Cibaduyut, perumahan ini menawarkan kemudahan akses menuju berbagai fasilitas dan area penting di sekitarnya, sehingga mendukung aktivitas sehari-hari dengan lebih praktis.","kind":"textarea","maxLength":3000},
      {"key":"section2.description2","label":"Deskripsi 2 — Dengan perencanaan kawasan yang mempertimbang…","group":"VISI KAWASAN","defaultValue":"Dengan perencanaan kawasan yang mempertimbangkan kebutuhan penghuni, Taman Cibaduyut Indah memadukan lokasi yang strategis, serta pilihan hunian dengan harga yang tetap terjangkau. Pengembangan Taman Cibaduyut Indah 1 hingga Taman Cibaduyut Indah 3 dilakukan secara bertahap untuk memberikan pilihan hunian yang dapat disesuaikan dengan kebutuhan keluarga anda.","kind":"textarea","maxLength":3000},
      {"key":"section2.text2","label":"Teks / label 2 — 500+","group":"VISI KAWASAN","defaultValue":"500+","kind":"text","maxLength":180},
      {"key":"section2.text3","label":"Teks / label 3 — UNIT TERHUNI","group":"VISI KAWASAN","defaultValue":"UNIT TERHUNI","kind":"text","maxLength":180},
      {"key":"section2.text4","label":"Teks / label 4 — 55 Ha","group":"VISI KAWASAN","defaultValue":"55 Ha","kind":"text","maxLength":180},
      {"key":"section2.text5","label":"Teks / label 5 — TOTAL AREA","group":"VISI KAWASAN","defaultValue":"TOTAL AREA","kind":"text","maxLength":180},
      {"key":"section3.text","label":"Teks / label — PROYEK KAMI","group":"EKSPLORASI FASE","defaultValue":"PROYEK KAMI","kind":"text","maxLength":180},
      {"key":"section3.heading","label":"Judul bagian — Eksplorasi Fase Pengembangan","group":"EKSPLORASI FASE","defaultValue":"Eksplorasi Fase Pengembangan","kind":"text","maxLength":180},
      {"key":"section3.description","label":"Deskripsi — Pilih komplek yang sesuai dengan gaya hidup d…","group":"EKSPLORASI FASE","defaultValue":"Pilih komplek yang sesuai dengan gaya hidup dan kebutuhan masa depan Anda.","kind":"textarea","maxLength":3000},
      {"key":"price","label":"Harga mulai (Rupiah) pada kartu beranda","group":"Harga","defaultValue":"400000000","kind":"number","maxLength":180},
      {"key":"card.description","label":"Deskripsi kartu daftar proyek","group":"Kartu ringkasan","defaultValue":"Pilihan hunian terlengkap dengan berbagai tipe unit di pusat kota.","kind":"textarea","maxLength":3000},
    ],
  },
  {
    id: "rancamanyar", label: "Rancamanyar Indah", path: "/proyek/rancamanyar-indah", category: "Komplek",
    fields: [
      {"key":"strategicPoints.0","label":"Akses 1","group":"Lokasi — akses sekitar","defaultValue":"Terhubung ke Baleendah dan Bojongsoang","kind":"text","maxLength":180},
      {"key":"strategicPoints.1","label":"Akses 2","group":"Lokasi — akses sekitar","defaultValue":"Dekat dengan fasilitas pendidikan","kind":"text","maxLength":180},
      {"key":"strategicPoints.2","label":"Akses 3","group":"Lokasi — akses sekitar","defaultValue":"Akses menuju fasilitas kesehatan","kind":"text","maxLength":180},
      {"key":"strategicPoints.3","label":"Akses 4","group":"Lokasi — akses sekitar","defaultValue":"Dekat dengan kebutuhan harian keluarga","kind":"text","maxLength":180},
      {"key":"hero.title","label":"Judul halaman — Rancamanyar Indah","group":"HERO","defaultValue":"Rancamanyar Indah","kind":"text","maxLength":180},
      {"key":"hero.text","label":"Teks / label — Baleendah, Kabupaten Bandung","group":"HERO","defaultValue":"Baleendah, Kabupaten Bandung","kind":"text","maxLength":180},
      {"key":"hero.description","label":"Deskripsi — Kawasan hunian dengan harga terjangkau dan lo…","group":"HERO","defaultValue":"Kawasan hunian dengan harga terjangkau dan lokasi strategis untuk keluarga anda.","kind":"textarea","maxLength":3000},
      {"key":"section2.text","label":"Teks / label — RANCAMANYAR INDAH","group":"INTRO KOMPLEK","defaultValue":"RANCAMANYAR INDAH","kind":"text","maxLength":180},
      {"key":"section2.heading","label":"Judul bagian — Hunian Terjangkau di Kawasan Berkembang","group":"INTRO KOMPLEK","defaultValue":"Hunian Terjangkau di Kawasan Berkembang","kind":"text","maxLength":180},
      {"key":"section2.description","label":"Deskripsi — Rancamanyar Indah adalah kawasan perumahan se…","group":"INTRO KOMPLEK","defaultValue":"Rancamanyar Indah adalah kawasan perumahan seluas 15 hektar yang dirancang untuk mendukung kebutuhan keluarga. Lingkungan yang tertata, akses praktis, dan pilihan hunian yang terjangkau menjadikannya tempat tinggal yang nyaman untuk bertumbuh.","kind":"textarea","maxLength":3000},
      {"key":"section2.text2","label":"Teks / label 2 — Kawasan 15 Hektar","group":"INTRO KOMPLEK","defaultValue":"Kawasan 15 Hektar","kind":"text","maxLength":180},
      {"key":"section2.text3","label":"Teks / label 3 — Lingkungan Tertata","group":"INTRO KOMPLEK","defaultValue":"Lingkungan Tertata","kind":"text","maxLength":180},
      {"key":"section2.text4","label":"Teks / label 4 — Keamanan 24/7","group":"INTRO KOMPLEK","defaultValue":"Keamanan 24/7","kind":"text","maxLength":180},
      {"key":"section3.text","label":"Teks / label — RANCAMANYAR INDAH","group":"GALERI UNIT","defaultValue":"RANCAMANYAR INDAH","kind":"text","maxLength":180},
      {"key":"section3.heading","label":"Judul bagian — Galeri Unit","group":"GALERI UNIT","defaultValue":"Galeri Unit","kind":"text","maxLength":180},
      {"key":"section3.description","label":"Deskripsi — Jelajahi ruang tamu, kamar tidur, dan area be…","group":"GALERI UNIT","defaultValue":"Jelajahi ruang tamu, kamar tidur, dan area belakang hunian Rancamanyar Indah.","kind":"textarea","maxLength":3000},
      {"key":"section3.text2","label":"Teks / label 2 — Ruang Tamu","group":"GALERI UNIT","defaultValue":"Ruang Tamu","kind":"text","maxLength":180},
      {"key":"section4.text","label":"Teks / label — LOKASI KAMI","group":"LOKASI","defaultValue":"LOKASI KAMI","kind":"text","maxLength":180},
      {"key":"section4.heading","label":"Judul bagian — Lokasi Strategis","group":"LOKASI","defaultValue":"Lokasi Strategis","kind":"text","maxLength":180},
      {"key":"section4.description","label":"Deskripsi — Rancamanyar Indah berada di Baleendah, Kabupa…","group":"LOKASI","defaultValue":"Rancamanyar Indah berada di Baleendah, Kabupaten Bandung, dengan akses yang mendukung aktivitas keluarga menuju berbagai fasilitas di sekitarnya.","kind":"textarea","maxLength":3000},
      {"key":"gallery.label2","label":"Label foto 2","group":"Galeri — keterangan foto","defaultValue":"Kamar Tidur","kind":"text","maxLength":180},
      {"key":"gallery.label3","label":"Label foto 3","group":"Galeri — keterangan foto","defaultValue":"Area Belakang","kind":"text","maxLength":180},
      {"key":"price","label":"Harga mulai (Rupiah) pada kartu beranda","group":"Harga","defaultValue":"200000000","kind":"number","maxLength":180},
      {"key":"card.description","label":"Deskripsi kartu daftar proyek","group":"Kartu ringkasan","defaultValue":"Komplek perumahan dengan harga terjangkau dan berbagai pilihan unit.","kind":"textarea","maxLength":3000},
    ],
  },
  {
    id: "permata-buah-batu", label: "Permata Buah Batu", path: "/proyek/permata-buah-batu", category: "Komplek",
    fields: [
      {"key":"strategicPoints.0","label":"Akses 1","group":"Lokasi — akses sekitar","defaultValue":"Berada di kawasan Bojongsoang, Bandung","kind":"text","maxLength":180},
      {"key":"strategicPoints.1","label":"Akses 2","group":"Lokasi — akses sekitar","defaultValue":"Akses menuju pusat Kota Bandung","kind":"text","maxLength":180},
      {"key":"strategicPoints.2","label":"Akses 3","group":"Lokasi — akses sekitar","defaultValue":"Dekat dengan fasilitas pendidikan","kind":"text","maxLength":180},
      {"key":"strategicPoints.3","label":"Akses 4","group":"Lokasi — akses sekitar","defaultValue":"Dekat dengan pusat kebutuhan harian","kind":"text","maxLength":180},
      {"key":"hero.title","label":"Judul halaman — Permata Buah Batu","group":"HERO","defaultValue":"Permata Buah Batu","kind":"text","maxLength":180},
      {"key":"hero.text","label":"Teks / label — Bojongsoang, Kota Bandung","group":"HERO","defaultValue":"Bojongsoang, Kota Bandung","kind":"text","maxLength":180},
      {"key":"hero.description","label":"Deskripsi — Gaya hidup urban modern di tengah kota dengan…","group":"HERO","defaultValue":"Gaya hidup urban modern di tengah kota dengan harga terjangkau dan lokasi yang nyaman.","kind":"textarea","maxLength":3000},
      {"key":"section2.text","label":"Teks / label — PERMATA BUAH BATU","group":"INTRO KOMPLEK","defaultValue":"PERMATA BUAH BATU","kind":"text","maxLength":180},
      {"key":"section2.heading","label":"Judul bagian — Hunian Urban dalam Lingkungan Tertata","group":"INTRO KOMPLEK","defaultValue":"Hunian Urban dalam Lingkungan Tertata","kind":"text","maxLength":180},
      {"key":"section2.description","label":"Deskripsi — Gaya hidup urban yang modern menyatu dengan k…","group":"INTRO KOMPLEK","defaultValue":"Gaya hidup urban yang modern menyatu dengan kenyamanan lingkungan perumahan yang tertata rapi di kawasan Bojongsoang, Bandung.","kind":"textarea","maxLength":3000},
      {"key":"section2.text2","label":"Teks / label 2 — Kawasan Hunian Mapan","group":"INTRO KOMPLEK","defaultValue":"Kawasan Hunian Mapan","kind":"text","maxLength":180},
      {"key":"section2.text3","label":"Teks / label 3 — Lingkungan Tertata","group":"INTRO KOMPLEK","defaultValue":"Lingkungan Tertata","kind":"text","maxLength":180},
      {"key":"section2.text4","label":"Teks / label 4 — Keamanan Satu Pintu","group":"INTRO KOMPLEK","defaultValue":"Keamanan Satu Pintu","kind":"text","maxLength":180},
      {"key":"section3.text","label":"Teks / label — LOKASI KAMI","group":"LOKASI","defaultValue":"LOKASI KAMI","kind":"text","maxLength":180},
      {"key":"section3.heading","label":"Judul bagian — Lokasi Strategis","group":"LOKASI","defaultValue":"Lokasi Strategis","kind":"text","maxLength":180},
      {"key":"section3.description","label":"Deskripsi — Permata Buah Batu terletak di kawasan Bojongs…","group":"LOKASI","defaultValue":"Permata Buah Batu terletak di kawasan Bojongsoang dengan akses yang memudahkan penghuni menjangkau berbagai fasilitas penting di Bandung dan sekitarnya.","kind":"textarea","maxLength":3000},
      {"key":"price","label":"Harga mulai (Rupiah) pada kartu beranda","group":"Harga","defaultValue":"450000000","kind":"number","maxLength":180},
      {"key":"card.description","label":"Deskripsi kartu daftar proyek","group":"Kartu ringkasan","defaultValue":"Gaya hidup urban modern ditengah kota dengan harga terjangkau.","kind":"textarea","maxLength":3000},
    ],
  },
  {
    id: "tci-1", label: "TCI 1", path: "/proyek/tci/tci-1", category: "Fase TCI",
    fields: [
      {"key":"unitGallery.0.label","label":"Label foto 1","group":"Galeri — keterangan foto","defaultValue":"Ruang Tamu","kind":"text","maxLength":180},
      {"key":"unitGallery.1.label","label":"Label foto 2","group":"Galeri — keterangan foto","defaultValue":"Kamar Tidur","kind":"text","maxLength":180},
      {"key":"unitGallery.2.label","label":"Label foto 3","group":"Galeri — keterangan foto","defaultValue":"Dapur","kind":"text","maxLength":180},
      {"key":"strategicPoints.0","label":"Akses 1","group":"Lokasi — akses sekitar","defaultValue":"Terhubung dengan kawasan Cibaduyut","kind":"text","maxLength":180},
      {"key":"strategicPoints.1","label":"Akses 2","group":"Lokasi — akses sekitar","defaultValue":"Akses menuju pusat Kota Bandung","kind":"text","maxLength":180},
      {"key":"strategicPoints.2","label":"Akses 3","group":"Lokasi — akses sekitar","defaultValue":"Dekat dengan fasilitas pendidikan","kind":"text","maxLength":180},
      {"key":"strategicPoints.3","label":"Akses 4","group":"Lokasi — akses sekitar","defaultValue":"Dekat dengan fasilitas kesehatan","kind":"text","maxLength":180},
      {"key":"hero.title","label":"Judul halaman — Taman Cibaduyut Indah 1","group":"HERO","defaultValue":"Taman Cibaduyut Indah 1","kind":"text","maxLength":180},
      {"key":"hero.text","label":"Teks / label — Cibaduyut, Kota Bandung","group":"HERO","defaultValue":"Cibaduyut, Kota Bandung","kind":"text","maxLength":180},
      {"key":"hero.description","label":"Deskripsi — Fondasi utama dalam pembangunan kawasan hunia…","group":"HERO","defaultValue":"Fondasi utama dalam pembangunan kawasan hunian terpadu yang terjangkau dan strategis.","kind":"textarea","maxLength":3000},
      {"key":"section2.text","label":"Teks / label — TAMAN CIBADUYUT INDAH","group":"INTRO KOMPLEK","defaultValue":"TAMAN CIBADUYUT INDAH","kind":"text","maxLength":180},
      {"key":"section2.heading","label":"Judul bagian — Hunian Nyaman dalam Komunitas Mapan","group":"INTRO KOMPLEK","defaultValue":"Hunian Nyaman dalam Komunitas Mapan","kind":"text","maxLength":180},
      {"key":"section2.description","label":"Deskripsi — Taman Cibaduyut Indah 1 menghadirkan lingkung…","group":"INTRO KOMPLEK","defaultValue":"Taman Cibaduyut Indah 1 menghadirkan lingkungan hunian yang telah berkembang dan nyaman bagi keluarga. Kawasan yang rindang, suasana komunitas yang hangat, serta pengelolaan keamanan yang terjaga menjadikan TCI 1 pilihan hunian untuk kehidupan keluarga yang tenang dan harmonis.","kind":"textarea","maxLength":3000},
      {"key":"section2.text2","label":"Teks / label 2 — Established Community","group":"INTRO KOMPLEK","defaultValue":"Established Community","kind":"text","maxLength":180},
      {"key":"section2.text3","label":"Teks / label 3 — Lingkungan Asri","group":"INTRO KOMPLEK","defaultValue":"Lingkungan Asri","kind":"text","maxLength":180},
      {"key":"section2.text4","label":"Teks / label 4 — Keamanan Terjaga","group":"INTRO KOMPLEK","defaultValue":"Keamanan Terjaga","kind":"text","maxLength":180},
      {"key":"section3.text","label":"Teks / label — TAMAN CIBADUYUT INDAH 1","group":"GALERI UNIT","defaultValue":"TAMAN CIBADUYUT INDAH 1","kind":"text","maxLength":180},
      {"key":"section3.heading","label":"Judul bagian — Galeri Unit","group":"GALERI UNIT","defaultValue":"Galeri Unit","kind":"text","maxLength":180},
      {"key":"section3.description","label":"Deskripsi — Intip setiap sudut hunian di Taman Cibaduyut …","group":"GALERI UNIT","defaultValue":"Intip setiap sudut hunian di Taman Cibaduyut Indah 1.","kind":"textarea","maxLength":3000},
      {"key":"section4.text","label":"Teks / label — LOKASI KAMI","group":"LOKASI","defaultValue":"LOKASI KAMI","kind":"text","maxLength":180},
      {"key":"section4.heading","label":"Judul bagian — Lokasi Strategis","group":"LOKASI","defaultValue":"Lokasi Strategis","kind":"text","maxLength":180},
      {"key":"section4.description","label":"Deskripsi — TCI 1 berada di kawasan Cibaduyut dengan akse…","group":"LOKASI","defaultValue":"TCI 1 berada di kawasan Cibaduyut dengan akses yang mendukung kebutuhan aktivitas harian penghuni menuju berbagai fasilitas penting di Bandung dan sekitarnya.","kind":"textarea","maxLength":3000},
      {"key":"card.description","label":"Deskripsi kartu di halaman TCI","group":"Kartu ringkasan","defaultValue":"Komunitas yang telah mapan dengan lingkungan hijau yang rindang dan keamanan 24 jam yang ketat.","kind":"textarea","maxLength":3000},
    ],
  },
  {
    id: "tci-2", label: "TCI 2", path: "/proyek/tci/tci-2", category: "Fase TCI",
    fields: [
      {"key":"unitGallery.0.label","label":"Label foto 1","group":"Galeri — keterangan foto","defaultValue":"Ruang Tamu","kind":"text","maxLength":180},
      {"key":"unitGallery.1.label","label":"Label foto 2","group":"Galeri — keterangan foto","defaultValue":"Kamar Tidur","kind":"text","maxLength":180},
      {"key":"unitGallery.2.label","label":"Label foto 3","group":"Galeri — keterangan foto","defaultValue":"Dapur","kind":"text","maxLength":180},
      {"key":"strategicPoints.0","label":"Akses 1","group":"Lokasi — akses sekitar","defaultValue":"Terhubung dengan kawasan Cibaduyut","kind":"text","maxLength":180},
      {"key":"strategicPoints.1","label":"Akses 2","group":"Lokasi — akses sekitar","defaultValue":"Akses menuju pusat Kota Bandung","kind":"text","maxLength":180},
      {"key":"strategicPoints.2","label":"Akses 3","group":"Lokasi — akses sekitar","defaultValue":"Dekat dengan fasilitas pendidikan","kind":"text","maxLength":180},
      {"key":"strategicPoints.3","label":"Akses 4","group":"Lokasi — akses sekitar","defaultValue":"Dekat dengan fasilitas kesehatan","kind":"text","maxLength":180},
      {"key":"hero.title","label":"Judul halaman — Taman Cibaduyut Indah 2","group":"HERO","defaultValue":"Taman Cibaduyut Indah 2","kind":"text","maxLength":180},
      {"key":"hero.text","label":"Teks / label — Cibaduyut, Kota Bandung","group":"HERO","defaultValue":"Cibaduyut, Kota Bandung","kind":"text","maxLength":180},
      {"key":"hero.description","label":"Deskripsi — Pengembangan kawasan hunian modern yang menaw…","group":"HERO","defaultValue":"Pengembangan kawasan hunian modern yang menawarkan harga yang terjangkau.","kind":"textarea","maxLength":3000},
      {"key":"section2.text","label":"Teks / label — TAMAN CIBADUYUT INDAH","group":"INTRO KOMPLEK","defaultValue":"TAMAN CIBADUYUT INDAH","kind":"text","maxLength":180},
      {"key":"section2.heading","label":"Judul bagian — Hunian Minimalis untuk Keluarga Modern","group":"INTRO KOMPLEK","defaultValue":"Hunian Minimalis untuk Keluarga Modern","kind":"text","maxLength":180},
      {"key":"section2.description","label":"Deskripsi — Taman Cibaduyut Indah 2 dikembangkan dengan k…","group":"INTRO KOMPLEK","defaultValue":"Taman Cibaduyut Indah 2 dikembangkan dengan konsep hunian minimalis modern yang mengutamakan efisiensi ruang dan kenyamanan keluarga. Perencanaan bangunan yang fungsional serta pemanfaatan pencahayaan alami menciptakan lingkungan tempat tinggal yang nyaman untuk aktivitas sehari-hari.","kind":"textarea","maxLength":3000},
      {"key":"section2.text2","label":"Teks / label 2 — Modern Development","group":"INTRO KOMPLEK","defaultValue":"Modern Development","kind":"text","maxLength":180},
      {"key":"section2.text3","label":"Teks / label 3 — Pencahayaan Alami","group":"INTRO KOMPLEK","defaultValue":"Pencahayaan Alami","kind":"text","maxLength":180},
      {"key":"section2.text4","label":"Teks / label 4 — Family Oriented","group":"INTRO KOMPLEK","defaultValue":"Family Oriented","kind":"text","maxLength":180},
      {"key":"section3.text","label":"Teks / label — TAMAN CIBADUYUT INDAH 2","group":"GALERI UNIT","defaultValue":"TAMAN CIBADUYUT INDAH 2","kind":"text","maxLength":180},
      {"key":"section3.heading","label":"Judul bagian — Galeri Unit","group":"GALERI UNIT","defaultValue":"Galeri Unit","kind":"text","maxLength":180},
      {"key":"section3.description","label":"Deskripsi — Intip setiap sudut hunian di Taman Cibaduyut …","group":"GALERI UNIT","defaultValue":"Intip setiap sudut hunian di Taman Cibaduyut Indah 2.","kind":"textarea","maxLength":3000},
      {"key":"section4.text","label":"Teks / label — LOKASI KAMI","group":"LOKASI","defaultValue":"LOKASI KAMI","kind":"text","maxLength":180},
      {"key":"section4.heading","label":"Judul bagian — Lokasi Strategis","group":"LOKASI","defaultValue":"Lokasi Strategis","kind":"text","maxLength":180},
      {"key":"section4.description","label":"Deskripsi — TCI 2 berada di kawasan Cibaduyut dengan akse…","group":"LOKASI","defaultValue":"TCI 2 berada di kawasan Cibaduyut dengan akses yang mendukung mobilitas penghuni menuju pusat aktivitas dan berbagai fasilitas umum di Bandung dan sekitarnya.","kind":"textarea","maxLength":3000},
      {"key":"card.description","label":"Deskripsi kartu di halaman TCI","group":"Kartu ringkasan","defaultValue":"Konsep hunian minimalis modern yang mengedepankan efisiensi ruang dan pencahayaan alami maksimal.","kind":"textarea","maxLength":3000},
    ],
  },
  {
    id: "tci-3", label: "TCI 3", path: "/proyek/tci/tci-3", category: "Fase TCI",
    fields: [
      {"key":"strategicPoints.0","label":"Akses 1","group":"Lokasi — akses sekitar","defaultValue":"Gerbang Tol Kopo","kind":"text","maxLength":180},
      {"key":"strategicPoints.1","label":"Akses 2","group":"Lokasi — akses sekitar","defaultValue":"Mulia Wacana Kindergarten","kind":"text","maxLength":180},
      {"key":"strategicPoints.2","label":"Akses 3","group":"Lokasi — akses sekitar","defaultValue":"Rumah Sakit Umum Daerah Bandung Kiwari","kind":"text","maxLength":180},
      {"key":"strategicPoints.3","label":"Akses 4","group":"Lokasi — akses sekitar","defaultValue":"Pasar Cibiuk Moh. Toha","kind":"text","maxLength":180},
      {"key":"hero.title","label":"Judul halaman — Taman Cibaduyut Indah 3","group":"HERO","defaultValue":"Taman Cibaduyut Indah 3","kind":"text","maxLength":180},
      {"key":"hero.text","label":"Teks / label — Cibaduyut, Kota Bandung","group":"HERO","defaultValue":"Cibaduyut, Kota Bandung","kind":"text","maxLength":180},
      {"key":"hero.description","label":"Deskripsi — Konsep hunian cluster terbaru yang terjangkau…","group":"HERO","defaultValue":"Konsep hunian cluster terbaru yang terjangkau dan nyaman dengan desain modern.","kind":"textarea","maxLength":3000},
      {"key":"section2.text","label":"Teks / label — TAMAN CIBADUYUT INDAH","group":"INTRO KOMPLEK","defaultValue":"TAMAN CIBADUYUT INDAH","kind":"text","maxLength":180},
      {"key":"section2.heading","label":"Judul bagian — Konsep Hunian Modern & Masa Depan","group":"INTRO KOMPLEK","defaultValue":"Konsep Hunian Modern & Masa Depan","kind":"text","maxLength":180},
      {"key":"section2.description","label":"Deskripsi — Taman Cibaduyut Indah 3 menghadirkan standar …","group":"INTRO KOMPLEK","defaultValue":"Taman Cibaduyut Indah 3 menghadirkan standar baru dalam pengembangan kawasan hunian terpadu. Didesain dengan filosofi fleksibilitas ruang, setiap unit di TCI 3 memungkinkan penghuni untuk menyesuaikan tata letak seiring dengan perkembangan kebutuhan keluarga.","kind":"textarea","maxLength":3000},
      {"key":"section2.text2","label":"Teks / label 2 — Future-Ready Design","group":"INTRO KOMPLEK","defaultValue":"Future-Ready Design","kind":"text","maxLength":180},
      {"key":"section2.text3","label":"Teks / label 3 — Family Oriented","group":"INTRO KOMPLEK","defaultValue":"Family Oriented","kind":"text","maxLength":180},
      {"key":"section2.text4","label":"Teks / label 4 — 3 Tipe Eksklusif","group":"INTRO KOMPLEK","defaultValue":"3 Tipe Eksklusif","kind":"text","maxLength":180},
      {"key":"section3.text","label":"Teks / label — TIPE RUMAH","group":"PILIH TIPE BANGUNAN","defaultValue":"TIPE RUMAH","kind":"text","maxLength":180},
      {"key":"section3.heading","label":"Judul bagian — Pilih Tipe Bangunan Anda","group":"PILIH TIPE BANGUNAN","defaultValue":"Pilih Tipe Bangunan Anda","kind":"text","maxLength":180},
      {"key":"section3.description","label":"Deskripsi — Investasi cerdas untuk kenyamanan keluarga ja…","group":"PILIH TIPE BANGUNAN","defaultValue":"Investasi cerdas untuk kenyamanan keluarga jangka panjang","kind":"textarea","maxLength":3000},
      {"key":"section4.text","label":"Teks / label — SPESIFIKASI","group":"SPESIFIKASI (PAS DI HP TANPA SCROLL)","defaultValue":"SPESIFIKASI","kind":"text","maxLength":180},
      {"key":"section4.heading","label":"Judul bagian — Spesifikasi Unit","group":"SPESIFIKASI (PAS DI HP TANPA SCROLL)","defaultValue":"Spesifikasi Unit","kind":"text","maxLength":180},
      {"key":"section5.text","label":"Teks / label — LOKASI KAMI","group":"LOKASI","defaultValue":"LOKASI KAMI","kind":"text","maxLength":180},
      {"key":"section5.heading","label":"Judul bagian — Lokasi Strategis","group":"LOKASI","defaultValue":"Lokasi Strategis","kind":"text","maxLength":180},
      {"key":"section5.description","label":"Deskripsi — TCI 3 terletak di jantung area berkembang Cib…","group":"LOKASI","defaultValue":"TCI 3 terletak di jantung area berkembang Cibaduyut, memberikan akses cepat ke pusat kota Bandung dan fasilitas umum utama.","kind":"textarea","maxLength":3000},
      {"key":"card.description","label":"Deskripsi kartu di halaman TCI","group":"Kartu ringkasan","defaultValue":"Fase terbaru dengan desain arsitektur kontemporer dan integrasi smart home system yang cerdas.","kind":"textarea","maxLength":3000},
    ],
  },
  {
    id: "tipe-36", label: "TCI 3 — Cluster Tipe 36", path: "/proyek/tci/tci-3/tipe-36", category: "Tipe unit",
    fields: [
      {"key":"specs.0.value","label":"LUAS TANAH","group":"Spesifikasi","defaultValue":"72 m²","kind":"text","maxLength":180},
      {"key":"specs.1.value","label":"LUAS BANGUNAN","group":"Spesifikasi","defaultValue":"36 m²","kind":"text","maxLength":180},
      {"key":"specs.2.value","label":"KAMAR TIDUR","group":"Spesifikasi","defaultValue":"2 Kamar","kind":"text","maxLength":180},
      {"key":"specs.3.value","label":"KAMAR MANDI","group":"Spesifikasi","defaultValue":"1 Kamar","kind":"text","maxLength":180},
      {"key":"specs.4.value","label":"CARPORT","group":"Spesifikasi","defaultValue":"1 Mobil","kind":"text","maxLength":180},
      {"key":"specs.5.value","label":"LISTRIK","group":"Spesifikasi","defaultValue":"2200 VA","kind":"text","maxLength":180},
      {"key":"floorPlanSteps.0.title","label":"Judul 1","group":"Denah — poin keterangan","defaultValue":"Open Plan Living","kind":"text","maxLength":180},
      {"key":"floorPlanSteps.0.description","label":"Deskripsi 1","group":"Denah — poin keterangan","defaultValue":"Ruang tamu dan ruang makan yang menyatu memberikan kesan luas pada interior rumah.","kind":"textarea","maxLength":3000},
      {"key":"floorPlanSteps.1.title","label":"Judul 2","group":"Denah — poin keterangan","defaultValue":"Dual Bedroom","kind":"text","maxLength":180},
      {"key":"floorPlanSteps.1.description","label":"Deskripsi 2","group":"Denah — poin keterangan","defaultValue":"Dua kamar tidur yang terpisah memberikan privasi maksimal untuk orang tua dan anak.","kind":"textarea","maxLength":3000},
      {"key":"floorPlanSteps.2.title","label":"Judul 3","group":"Denah — poin keterangan","defaultValue":"Sirkulasi Udara Optimal","kind":"text","maxLength":180},
      {"key":"floorPlanSteps.2.description","label":"Deskripsi 3","group":"Denah — poin keterangan","defaultValue":"Penempatan jendela strategis di bagian depan dan belakang menjamin pertukaran udara yang baik.","kind":"textarea","maxLength":3000},
      {"key":"hero.text","label":"Teks / label — PREMIUM RESIDENTIAL","group":"HERO","defaultValue":"PREMIUM RESIDENTIAL","kind":"text","maxLength":180},
      {"key":"hero.title","label":"Judul halaman — TCI 3 — Tipe 36","group":"HERO","defaultValue":"TCI 3 — Tipe 36","kind":"text","maxLength":180},
      {"key":"hero.description","label":"Deskripsi — Tipe 36 dirancang sebagai hunian modern denga…","group":"HERO","defaultValue":"Tipe 36 dirancang sebagai hunian modern dengan tata ruang efisien, memaksimalkan setiap meter persegi untuk kenyamanan dan fungsionalitas.","kind":"textarea","maxLength":3000},
      {"key":"section2.text","label":"Teks / label — SPESIFIKASI","group":"SPESIFIKASI EKSKLUSIF","defaultValue":"SPESIFIKASI","kind":"text","maxLength":180},
      {"key":"section2.heading","label":"Judul bagian — Spesifikasi Eksklusif","group":"SPESIFIKASI EKSKLUSIF","defaultValue":"Spesifikasi Eksklusif","kind":"text","maxLength":180},
      {"key":"section3.text","label":"Teks / label — GAMBARAN RUMAH","group":"DENAH RUMAH","defaultValue":"GAMBARAN RUMAH","kind":"text","maxLength":180},
      {"key":"section3.heading","label":"Judul bagian — Denah Rumah","group":"DENAH RUMAH","defaultValue":"Denah Rumah","kind":"text","maxLength":180},
      {"key":"section3.description","label":"Deskripsi — Visualisasi tata ruang yang efisien, mengopti…","group":"DENAH RUMAH","defaultValue":"Visualisasi tata ruang yang efisien, mengoptimalkan setiap meter persegi untuk mendukung aktivitas harian Anda.","kind":"textarea","maxLength":3000},
      {"key":"section4.text","label":"Teks / label — UNIT TIPE 36","group":"GALERI UNIT","defaultValue":"UNIT TIPE 36","kind":"text","maxLength":180},
      {"key":"section4.heading","label":"Judul bagian — Galeri Unit","group":"GALERI UNIT","defaultValue":"Galeri Unit","kind":"text","maxLength":180},
      {"key":"section4.description","label":"Deskripsi — Intip setiap sudut hunian impian Anda.","group":"GALERI UNIT","defaultValue":"Intip setiap sudut hunian impian Anda.","kind":"textarea","maxLength":3000},
      {"key":"section4.text2","label":"Teks / label 2 — Ruang Tamu","group":"GALERI UNIT","defaultValue":"Ruang Tamu","kind":"text","maxLength":180},
      {"key":"section4.text3","label":"Teks / label 3 — Kamar Tidur Utama","group":"GALERI UNIT","defaultValue":"Kamar Tidur Utama","kind":"text","maxLength":180},
      {"key":"section4.text4","label":"Teks / label 4 — Kamar Anak","group":"GALERI UNIT","defaultValue":"Kamar Anak","kind":"text","maxLength":180},
      {"key":"price","label":"Harga awal (Rupiah) — kartu tipe & simulasi KPR","group":"Harga","defaultValue":"450000000","kind":"number","maxLength":180},
      {"key":"card.title","label":"Nama pada kartu tipe","group":"Kartu ringkasan","defaultValue":"Tipe 36","kind":"text","maxLength":180},
      {"key":"card.description","label":"Deskripsi kartu tipe","group":"Kartu ringkasan","defaultValue":"Compact, efficient, and beautifully designed for young couples.","kind":"textarea","maxLength":3000},
    ],
  },
  {
    id: "tipe-45", label: "TCI 3 — Cluster Tipe 45", path: "/proyek/tci/tci-3/tipe-45", category: "Tipe unit",
    fields: [
      {"key":"specs.0.value","label":"LUAS TANAH","group":"Spesifikasi","defaultValue":"90 m²","kind":"text","maxLength":180},
      {"key":"specs.1.value","label":"LUAS BANGUNAN","group":"Spesifikasi","defaultValue":"45 m²","kind":"text","maxLength":180},
      {"key":"specs.2.value","label":"KAMAR TIDUR","group":"Spesifikasi","defaultValue":"2 Kamar","kind":"text","maxLength":180},
      {"key":"specs.3.value","label":"KAMAR MANDI","group":"Spesifikasi","defaultValue":"1 Kamar","kind":"text","maxLength":180},
      {"key":"specs.4.value","label":"CARPORT","group":"Spesifikasi","defaultValue":"1 Mobil","kind":"text","maxLength":180},
      {"key":"specs.5.value","label":"LISTRIK","group":"Spesifikasi","defaultValue":"2200 VA","kind":"text","maxLength":180},
      {"key":"floorPlanPoints.0.title","label":"Judul 1","group":"Denah — poin keterangan","defaultValue":"Ruang Keluarga Lebih Luas","kind":"text","maxLength":180},
      {"key":"floorPlanPoints.0.description","label":"Deskripsi 1","group":"Denah — poin keterangan","defaultValue":"Area ruang keluarga dirancang lebih lega untuk memberikan kenyamanan saat berkumpul bersama keluarga.","kind":"textarea","maxLength":3000},
      {"key":"floorPlanPoints.1.title","label":"Judul 2","group":"Denah — poin keterangan","defaultValue":"Dua Kamar Tidur","kind":"text","maxLength":180},
      {"key":"floorPlanPoints.1.description","label":"Deskripsi 2","group":"Denah — poin keterangan","defaultValue":"Dua kamar tidur ditempatkan secara strategis untuk memberikan kenyamanan dan privasi bagi penghuni.","kind":"textarea","maxLength":3000},
      {"key":"floorPlanPoints.2.title","label":"Judul 3","group":"Denah — poin keterangan","defaultValue":"Pencahayaan Alami","kind":"text","maxLength":180},
      {"key":"floorPlanPoints.2.description","label":"Deskripsi 3","group":"Denah — poin keterangan","defaultValue":"Penempatan pintu dan jendela membantu memaksimalkan pencahayaan alami serta sirkulasi udara.","kind":"textarea","maxLength":3000},
      {"key":"hero.text","label":"Teks / label — PREMIUM RESIDENTIAL","group":"HERO","defaultValue":"PREMIUM RESIDENTIAL","kind":"text","maxLength":180},
      {"key":"hero.title","label":"Judul halaman — TCI 3 — Tipe 45","group":"HERO","defaultValue":"TCI 3 — Tipe 45","kind":"text","maxLength":180},
      {"key":"hero.description","label":"Deskripsi — Tipe 45 dirancang sebagai hunian modern yang …","group":"HERO","defaultValue":"Tipe 45 dirancang sebagai hunian modern yang dirancang untuk keluarga anda, dengan tata ruang yang efisien dan fungsional.","kind":"textarea","maxLength":3000},
      {"key":"section2.text","label":"Teks / label — SPESIFIKASI","group":"SPESIFIKASI","defaultValue":"SPESIFIKASI","kind":"text","maxLength":180},
      {"key":"section2.heading","label":"Judul bagian — Spesifikasi Tipe 45","group":"SPESIFIKASI","defaultValue":"Spesifikasi Tipe 45","kind":"text","maxLength":180},
      {"key":"section3.text","label":"Teks / label — GAMBARAN RUMAH","group":"DENAH RUMAH","defaultValue":"GAMBARAN RUMAH","kind":"text","maxLength":180},
      {"key":"section3.heading","label":"Judul bagian — Denah Rumah Tipe 45","group":"DENAH RUMAH","defaultValue":"Denah Rumah Tipe 45","kind":"text","maxLength":180},
      {"key":"section3.description","label":"Deskripsi — Visualisasi tata ruang yang dirancang untuk m…","group":"DENAH RUMAH","defaultValue":"Visualisasi tata ruang yang dirancang untuk memaksimalkan kenyamanan dan fungsi pada setiap bagian rumah.","kind":"textarea","maxLength":3000},
      {"key":"section4.text","label":"Teks / label — UNIT TIPE 45","group":"GALERI UNIT","defaultValue":"UNIT TIPE 45","kind":"text","maxLength":180},
      {"key":"section4.heading","label":"Judul bagian — Galeri Unit","group":"GALERI UNIT","defaultValue":"Galeri Unit","kind":"text","maxLength":180},
      {"key":"section4.description","label":"Deskripsi — Intip setiap sudut hunian impian Anda.","group":"GALERI UNIT","defaultValue":"Intip setiap sudut hunian impian Anda.","kind":"textarea","maxLength":3000},
      {"key":"section4.text2","label":"Teks / label 2 — Dapur","group":"GALERI UNIT","defaultValue":"Dapur","kind":"text","maxLength":180},
      {"key":"section4.text3","label":"Teks / label 3 — Kamar Tidur Utama","group":"GALERI UNIT","defaultValue":"Kamar Tidur Utama","kind":"text","maxLength":180},
      {"key":"section4.text4","label":"Teks / label 4 — Kamar Anak","group":"GALERI UNIT","defaultValue":"Kamar Anak","kind":"text","maxLength":180},
      {"key":"price","label":"Harga awal (Rupiah) — kartu tipe & simulasi KPR","group":"Harga","defaultValue":"500000000","kind":"number","maxLength":180},
      {"key":"card.title","label":"Nama pada kartu tipe","group":"Kartu ringkasan","defaultValue":"Tipe 45","kind":"text","maxLength":180},
      {"key":"card.description","label":"Deskripsi kartu tipe","group":"Kartu ringkasan","defaultValue":"Extra space for growing families with premium finishes.","kind":"textarea","maxLength":3000},
    ],
  },
  {
    id: "tipe-50", label: "TCI 3 — Cluster Tipe 50", path: "/proyek/tci/tci-3/tipe-50", category: "Tipe unit",
    fields: [
      {"key":"specs.0.value","label":"LUAS TANAH","group":"Spesifikasi","defaultValue":"120 m²","kind":"text","maxLength":180},
      {"key":"specs.1.value","label":"LUAS BANGUNAN","group":"Spesifikasi","defaultValue":"50 m²","kind":"text","maxLength":180},
      {"key":"specs.2.value","label":"KAMAR TIDUR","group":"Spesifikasi","defaultValue":"2 Kamar","kind":"text","maxLength":180},
      {"key":"specs.3.value","label":"KAMAR MANDI","group":"Spesifikasi","defaultValue":"1 Kamar","kind":"text","maxLength":180},
      {"key":"specs.4.value","label":"CARPORT","group":"Spesifikasi","defaultValue":"1 Mobil","kind":"text","maxLength":180},
      {"key":"specs.5.value","label":"LISTRIK","group":"Spesifikasi","defaultValue":"2200 VA","kind":"text","maxLength":180},
      {"key":"floorPlanSteps.0.title","label":"Judul 1","group":"Denah — poin keterangan","defaultValue":"Open Plan Living","kind":"text","maxLength":180},
      {"key":"floorPlanSteps.0.description","label":"Deskripsi 1","group":"Denah — poin keterangan","defaultValue":"Ruang tamu dan ruang makan dirancang menyatu untuk menciptakan suasana yang lebih lapang dan nyaman.","kind":"textarea","maxLength":3000},
      {"key":"floorPlanSteps.1.title","label":"Judul 2","group":"Denah — poin keterangan","defaultValue":"Dua Kamar Tidur","kind":"text","maxLength":180},
      {"key":"floorPlanSteps.1.description","label":"Deskripsi 2","group":"Denah — poin keterangan","defaultValue":"Dua kamar tidur dengan penataan ruang yang efisien memberikan privasi untuk seluruh anggota keluarga.","kind":"textarea","maxLength":3000},
      {"key":"floorPlanSteps.2.title","label":"Judul 3","group":"Denah — poin keterangan","defaultValue":"Sirkulasi Udara Optimal","kind":"text","maxLength":180},
      {"key":"floorPlanSteps.2.description","label":"Deskripsi 3","group":"Denah — poin keterangan","defaultValue":"Penempatan pintu dan jendela yang strategis membantu pencahayaan serta pertukaran udara alami.","kind":"textarea","maxLength":3000},
      {"key":"hero.text","label":"Teks / label — PREMIUM RESIDENTIAL","group":"HERO","defaultValue":"PREMIUM RESIDENTIAL","kind":"text","maxLength":180},
      {"key":"hero.title","label":"Judul halaman — TCI 3 — Tipe 50","group":"HERO","defaultValue":"TCI 3 — Tipe 50","kind":"text","maxLength":180},
      {"key":"hero.description","label":"Deskripsi — Tipe 50 dirancang sebagai hunian besar modern…","group":"HERO","defaultValue":"Tipe 50 dirancang sebagai hunian besar modern yang mengutamakan kenyamanan dan fungsionalitas, dengan harga terjangkau.","kind":"textarea","maxLength":3000},
      {"key":"section2.text","label":"Teks / label — SPESIFIKASI","group":"SPESIFIKASI","defaultValue":"SPESIFIKASI","kind":"text","maxLength":180},
      {"key":"section2.heading","label":"Judul bagian — Spesifikasi Tipe 50","group":"SPESIFIKASI","defaultValue":"Spesifikasi Tipe 50","kind":"text","maxLength":180},
      {"key":"section3.text","label":"Teks / label — GAMBARAN RUMAH","group":"DENAH RUMAH","defaultValue":"GAMBARAN RUMAH","kind":"text","maxLength":180},
      {"key":"section3.heading","label":"Judul bagian — Denah Rumah","group":"DENAH RUMAH","defaultValue":"Denah Rumah","kind":"text","maxLength":180},
      {"key":"section3.description","label":"Deskripsi — Visualisasi tata ruang Tipe 50 yang dirancang…","group":"DENAH RUMAH","defaultValue":"Visualisasi tata ruang Tipe 50 yang dirancang untuk memberikan kenyamanan dan pemanfaatan ruang secara optimal.","kind":"textarea","maxLength":3000},
      {"key":"price","label":"Harga awal (Rupiah) — kartu tipe & simulasi KPR","group":"Harga","defaultValue":"560000000","kind":"number","maxLength":180},
      {"key":"card.title","label":"Nama pada kartu tipe","group":"Kartu ringkasan","defaultValue":"Tipe 50","kind":"text","maxLength":180},
      {"key":"card.description","label":"Deskripsi kartu tipe","group":"Kartu ringkasan","defaultValue":"The ultimate expression of luxury and space for the elite.","kind":"textarea","maxLength":3000},
    ],
  },
  {
    id: "non-cluster-50", label: "TCI 3 — Non-Cluster Tipe 50", path: "/proyek/tci/tci-3/non-cluster/tipe-50", category: "Tipe unit",
    fields: [
      {"key":"specs.0.value","label":"LUAS TANAH","group":"Spesifikasi","defaultValue":"120 m²","kind":"text","maxLength":180},
      {"key":"specs.1.value","label":"LUAS BANGUNAN","group":"Spesifikasi","defaultValue":"50 m²","kind":"text","maxLength":180},
      {"key":"specs.2.value","label":"KAMAR TIDUR","group":"Spesifikasi","defaultValue":"2 Kamar","kind":"text","maxLength":180},
      {"key":"specs.3.value","label":"KAMAR MANDI","group":"Spesifikasi","defaultValue":"1 Kamar","kind":"text","maxLength":180},
      {"key":"specs.4.value","label":"CARPORT","group":"Spesifikasi","defaultValue":"1 Mobil","kind":"text","maxLength":180},
      {"key":"specs.5.value","label":"LISTRIK","group":"Spesifikasi","defaultValue":"2200 VA","kind":"text","maxLength":180},
      {"key":"floorPlanSteps.0.title","label":"Judul 1","group":"Denah — poin keterangan","defaultValue":"Akses Langsung","kind":"text","maxLength":180},
      {"key":"floorPlanSteps.0.desc","label":"Deskripsi 1","group":"Denah — poin keterangan","defaultValue":"Hunian non-cluster dengan akses langsung dari jalan lingkungan untuk mobilitas keluarga yang lebih praktis.","kind":"textarea","maxLength":3000},
      {"key":"floorPlanSteps.1.title","label":"Judul 2","group":"Denah — poin keterangan","defaultValue":"Tata Ruang Fungsional","kind":"text","maxLength":180},
      {"key":"floorPlanSteps.1.desc","label":"Deskripsi 2","group":"Denah — poin keterangan","defaultValue":"Ruang keluarga, kamar tidur, dan area servis dirancang untuk memenuhi kebutuhan hunian keluarga modern.","kind":"textarea","maxLength":3000},
      {"key":"floorPlanSteps.2.title","label":"Judul 3","group":"Denah — poin keterangan","defaultValue":"Sirkulasi Nyaman","kind":"text","maxLength":180},
      {"key":"floorPlanSteps.2.desc","label":"Deskripsi 3","group":"Denah — poin keterangan","defaultValue":"Susunan ruangan memberikan pencahayaan dan sirkulasi udara yang baik untuk kenyamanan sehari-hari.","kind":"textarea","maxLength":3000},
      {"key":"hero.text","label":"Teks / label — Non-Cluster Residence","group":"HERO","defaultValue":"Non-Cluster Residence","kind":"text","maxLength":180},
      {"key":"hero.title","label":"Judul halaman — TCI 3 — Tipe 50","group":"HERO","defaultValue":"TCI 3 — Tipe 50","kind":"text","maxLength":180},
      {"key":"hero.text2","label":"Teks / label 2 — Cibaduyut, Kota Bandung","group":"HERO","defaultValue":"Cibaduyut, Kota Bandung","kind":"text","maxLength":180},
      {"key":"section2.description","label":"Deskripsi — Spesifikasi","group":"SPESIFIKASI","defaultValue":"Spesifikasi","kind":"textarea","maxLength":3000},
      {"key":"section2.heading","label":"Judul bagian — Spesifikasi Tipe 50","group":"SPESIFIKASI","defaultValue":"Spesifikasi Tipe 50","kind":"text","maxLength":180},
      {"key":"section2.description2","label":"Deskripsi 2 — Hunian non-cluster yang nyaman dengan lahan l…","group":"SPESIFIKASI","defaultValue":"Hunian non-cluster yang nyaman dengan lahan luas, akses langsung, dan tata ruang fungsional untuk kebutuhan keluarga.","kind":"textarea","maxLength":3000},
      {"key":"section3.description","label":"Deskripsi — Denah Rumah","group":"DENAH RUMAH","defaultValue":"Denah Rumah","kind":"textarea","maxLength":3000},
      {"key":"section3.heading","label":"Judul bagian — Tata Ruang Tipe 50","group":"DENAH RUMAH","defaultValue":"Tata Ruang Tipe 50","kind":"text","maxLength":180},
      {"key":"section3.description2","label":"Deskripsi 2 — Dirancang untuk memberikan kenyamanan keluarg…","group":"DENAH RUMAH","defaultValue":"Dirancang untuk memberikan kenyamanan keluarga melalui pembagian ruang yang efisien dan mudah digunakan.","kind":"textarea","maxLength":3000},
      {"key":"section4.description","label":"Deskripsi — Galeri Unit","group":"GALERI UNIT","defaultValue":"Galeri Unit","kind":"textarea","maxLength":3000},
      {"key":"section4.heading","label":"Judul bagian — Tampilan Tipe 50 Non-Cluster","group":"GALERI UNIT","defaultValue":"Tampilan Tipe 50 Non-Cluster","kind":"text","maxLength":180},
      {"key":"section4.description2","label":"Deskripsi 2 — Lihat tampilan fasad hunian dan denah Tipe 50…","group":"GALERI UNIT","defaultValue":"Lihat tampilan fasad hunian dan denah Tipe 50 Non-Cluster di Taman Cibaduyut Indah 3.","kind":"textarea","maxLength":3000},
      {"key":"section4.description3","label":"Deskripsi 3 — Ruang Tamu & Keluarga","group":"GALERI UNIT","defaultValue":"Ruang Tamu & Keluarga","kind":"textarea","maxLength":3000},
      {"key":"section4.description4","label":"Deskripsi 4 — Kamar tidur","group":"GALERI UNIT","defaultValue":"Kamar tidur","kind":"textarea","maxLength":3000},
      {"key":"section4.description5","label":"Deskripsi 5 — Dapur dan ruang makan","group":"GALERI UNIT","defaultValue":"Dapur dan ruang makan","kind":"textarea","maxLength":3000},
      {"key":"price","label":"Harga awal (Rupiah) — kartu tipe & simulasi KPR","group":"Harga","defaultValue":"500000000","kind":"number","maxLength":180},
      {"key":"card.title","label":"Nama pada kartu tipe","group":"Kartu ringkasan","defaultValue":"Tipe 50","kind":"text","maxLength":180},
      {"key":"card.description","label":"Deskripsi kartu tipe","group":"Kartu ringkasan","defaultValue":"Hunian non-cluster dengan tata ruang fungsional dan akses langsung untuk kenyamanan keluarga.","kind":"textarea","maxLength":3000},
    ],
  },
  {
    id: "teranova", label: "Terranova Arcade", path: "/proyek/tci/tci-3/ruko/teranova", category: "Tipe unit",
    fields: [
      {"key":"specs.0.value","label":"FUNGSI","group":"Spesifikasi","defaultValue":"Komersial","kind":"text","maxLength":180},
      {"key":"specs.1.value","label":"JUMLAH LANTAI","group":"Spesifikasi","defaultValue":"2 Lantai","kind":"text","maxLength":180},
      {"key":"specs.2.value","label":"RUANG UTAMA","group":"Spesifikasi","defaultValue":"Area Usaha","kind":"text","maxLength":180},
      {"key":"specs.3.value","label":"TOILET","group":"Spesifikasi","defaultValue":"1 Unit","kind":"text","maxLength":180},
      {"key":"specs.4.value","label":"AREA PARKIR","group":"Spesifikasi","defaultValue":"Depan Unit","kind":"text","maxLength":180},
      {"key":"specs.5.value","label":"LISTRIK","group":"Spesifikasi","defaultValue":"2200 VA","kind":"text","maxLength":180},
      {"key":"layoutPoints.0.title","label":"Judul 1","group":"Denah — poin keterangan","defaultValue":"Area Usaha Fleksibel","kind":"text","maxLength":180},
      {"key":"layoutPoints.0.description","label":"Deskripsi 1","group":"Denah — poin keterangan","defaultValue":"Ruang utama dirancang fleksibel untuk mendukung berbagai kebutuhan bisnis, mulai dari toko, kantor, hingga layanan profesional.","kind":"textarea","maxLength":3000},
      {"key":"layoutPoints.1.title","label":"Judul 2","group":"Denah — poin keterangan","defaultValue":"Pemisahan Area yang Efisien","kind":"text","maxLength":180},
      {"key":"layoutPoints.1.description","label":"Deskripsi 2","group":"Denah — poin keterangan","defaultValue":"Pembagian dua lantai membantu memisahkan area pelayanan, operasional, dan ruang kerja agar aktivitas usaha lebih teratur.","kind":"textarea","maxLength":3000},
      {"key":"layoutPoints.2.title","label":"Judul 3","group":"Denah — poin keterangan","defaultValue":"Fasad Komersial Modern","kind":"text","maxLength":180},
      {"key":"layoutPoints.2.description","label":"Deskripsi 3","group":"Denah — poin keterangan","defaultValue":"Tampilan depan yang modern memberikan visibilitas baik dan membantu membangun citra profesional untuk bisnis Anda.","kind":"textarea","maxLength":3000},
      {"key":"hero.text","label":"Teks / label — Commercial Space","group":"HERO","defaultValue":"Commercial Space","kind":"text","maxLength":180},
      {"key":"hero.title","label":"Judul halaman — TCI 3 — Terranova Arcade","group":"HERO","defaultValue":"TCI 3 — Terranova Arcade","kind":"text","maxLength":180},
      {"key":"hero.description","label":"Deskripsi — Ruang komersial modern di kawasan TCI 3 yang …","group":"HERO","defaultValue":"Ruang komersial modern di kawasan TCI 3 yang dirancang untuk mendukung pertumbuhan dan visibilitas bisnis Anda.","kind":"textarea","maxLength":3000},
      {"key":"section2.text","label":"Teks / label — Spesifikasi","group":"SPESIFIKASI","defaultValue":"Spesifikasi","kind":"text","maxLength":180},
      {"key":"section2.heading","label":"Judul bagian — Spesifikasi Terranova Arcade","group":"SPESIFIKASI","defaultValue":"Spesifikasi Terranova Arcade","kind":"text","maxLength":180},
      {"key":"section3.text","label":"Teks / label — Denah Ruko","group":"DENAH RUKO","defaultValue":"Denah Ruko","kind":"text","maxLength":180},
      {"key":"section3.heading","label":"Judul bagian — Denah Terranova Arcade","group":"DENAH RUKO","defaultValue":"Denah Terranova Arcade","kind":"text","maxLength":180},
      {"key":"section3.description","label":"Deskripsi — Tata ruang komersial yang dirancang untuk mem…","group":"DENAH RUKO","defaultValue":"Tata ruang komersial yang dirancang untuk memberikan fleksibilitas, kenyamanan operasional, dan tampilan bisnis yang profesional.","kind":"textarea","maxLength":3000},
      {"key":"section4.text","label":"Teks / label — TERRANOVA ARCADE","group":"GALERI UNIT","defaultValue":"TERRANOVA ARCADE","kind":"text","maxLength":180},
      {"key":"section4.heading","label":"Judul bagian — Galeri Unit","group":"GALERI UNIT","defaultValue":"Galeri Unit","kind":"text","maxLength":180},
      {"key":"section4.description","label":"Deskripsi — Jelajahi ruang utama, teras, dan area dapur r…","group":"GALERI UNIT","defaultValue":"Jelajahi ruang utama, teras, dan area dapur ruko Terranova Arcade.","kind":"textarea","maxLength":3000},
      {"key":"section4.text2","label":"Teks / label 2 — Ruang Utama","group":"GALERI UNIT","defaultValue":"Ruang Utama","kind":"text","maxLength":180},
      {"key":"price","label":"Harga awal (Rupiah) — kartu tipe & simulasi KPR","group":"Harga","defaultValue":"800000000","kind":"number","maxLength":180},
      {"key":"card.title","label":"Nama pada kartu tipe","group":"Kartu ringkasan","defaultValue":"Terranova Arcade","kind":"text","maxLength":180},
      {"key":"card.description","label":"Deskripsi kartu tipe","group":"Kartu ringkasan","defaultValue":"The ultimate expression of luxury and space for the elite commercial activities.","kind":"textarea","maxLength":3000},
      {"key":"gallery.label2","label":"Label foto 2","group":"Galeri — keterangan foto","defaultValue":"Teras Ruko","kind":"text","maxLength":180},
      {"key":"gallery.label3","label":"Label foto 3","group":"Galeri — keterangan foto","defaultValue":"Area Dapur","kind":"text","maxLength":180},
    ],
  },
]

export const contentDocuments: ContentDocument[] = pageDocuments.map(doc => ({
  ...doc,
  fields: [...resourceFields(doc.id), ...(availabilityDefaults[doc.id] ? [
    { key: 'availability', label: 'Status ketersediaan unit', group: 'Ketersediaan unit', kind: 'availability' as const, defaultValue: availabilityDefaults[doc.id], maxLength: 20 },
    ...doc.fields,
  ] : doc.fields)],
}))
